spring.application.name=researchmate-mcp-server

server.port=8081

spring.ai.mcp.server.protocol=STREAMABLE

spring.ai.mcp.server.name=researchmate-mcp-server
spring.ai.mcp.server.version=1.0.0
semantic-scholar.base-url=https://api.semanticscholar.org
semantic-scholar.api-key=${SEMANTIC_SCHOLAR_API_KEY:}